Feature/en-7737-voip-call-logs
syncromatics/syncromatics-track-api pull request #104
Opened 2021-12-28 23:43 UTC by glenwperry

2022-01-24 22:14 UTC, thzinc requested changes

2022-01-24 22:14 UTC, thzinc commented on package.json
> +  "version": "3.27.1-EN-7737-beta.106",
This should be reverted before merging

2022-01-24 22:14 UTC, thzinc commented on src/resources/CallLog.js
> +class CallLog extends Resource {
This should be either `VoipCallRecord` (or perhaps `CallRecord`) to be in line with the models used in Track API

2022-01-24 23:04 UTC, thzinc commented
Resolves issue EN-8123

2022-01-25 21:30 UTC, BorisGanov-GMV approved these changes
LGTM

2022-01-25 21:59 UTC, thzinc approved these changes

2022-01-26 00:41 UTC, merged