(+semver: feature) added provision key parameter to pass on header an…
syncromatics/syncromatics-track-api pull request #93
Opened 2021-02-24 15:36 UTC by gsRayP

added provision key and unit tests

2021-02-24 16:59 UTC, cuevaskoch commented
Just a quick note, please make sure that your squash-and-merge commit message follows the [Angular commit message guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format) in order to generate the proper version tag.

Outside the scope of this PR, but we should probably convert this project to use semver as generated by gogitver to match all of our other projects.  I'll file a separate issue and we can discuss there.

2021-02-24 17:09 UTC, cuevaskoch requested changes

2021-02-24 17:09 UTC, cuevaskoch commented on src/resources/VoipTicket.js
> +    })
I think this exposes a bug in non-browser environment support by clobbering the required `Content-Type` and `Accept` headers that [are set by default in Client.js](https://github.com/syncromatics/syncromatics-track-api/blob/master/src/Client.js#L98).  Could you please update Client.js as well to take into account merging any `headers` object that's passed in with the default headers?

2021-02-25 17:39 UTC, thzinc approved these changes

2021-02-25 17:41 UTC, BorisGanov-GMV approved these changes
LGTM

2021-02-25 17:56 UTC, merged